# https://taskfile.dev

version: '3'

tasks:

  commit:
    cmds:
      - git add .
      - git commit -m "Updated mappings"

  gofmt:
    dir: webviewloader
    cmds:
      - go fmt

  generate:mappings:
    dir: scripts
    cmds:
      - go run update_version_mapping.go
      - task: gofmt
#      - task: commit

